package com.dinoterra.dinosaur.dino.enums;

public enum DinoType {
    Theropod,
    Sauropod,
    Ceratopsian,
    Stegosaur,
    Ankylosaur,
    Pachycephalosaur,
    Ornithopod,
    Pterosaur,
    Marine,
    Prosauropod,
    Titanosaur,
    Therizinosaur,
    Dromaeosaur,
    Spinosaur,
    Ornithomimosaur,
    Oviraptorosaur,
    Troodontid,
    Alvarezsaur,
    Heterodontosaur,
    Hadrosaur,
    Carcharodontosaurid,
    Noasaurid,
    Megaraptoran,
    Marginocephalian,
    Rugose,
    Sauropodomorph,
    Unknown,     
}
