spring.application.name=expedition
spring.datasource.url=jdbc:postgresql://localhost:5432/dinosaurs
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
server.port=8002