spring.application.name=security

spring.datasource.url=jdbc:postgresql://localhost:5432/dinosaurs
spring.datasource.username=postgres
spring.datasource.password=12345

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=user-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.datasource.hikari.auto-commit=false

spring.jpa.hibernate.ddl-auto=update
server.port=8003

